In [1]:

# 특정 열만 추출하는 예시, 과제하면서 참고

data_list = [
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35],
    [36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45],
    [46, 47, 48, 49, 50]
]


import numpy as np

arr = np.array(data_list)
selected1 = arr[:, [1, 3]]     # :은 '모든'의 의미, 모든 행

print("\nNumPy 배열로 열 1, 3 추출:")
print(selected1)


# 넘파이 배열 인덱스를 이용한 방법 설명

selected2= arr[:, 1:4]   #파이썬에서 종료 열은 하나 적게
print("\nNumPy 배열로 열 1~3열 추출:")
print(selected2)


selected3= arr[2:5, 1:4]   # 2~4행, 1~3열 추출
print("\nNumPy 배열로 열 1~3열 추출:")
print(selected3)


# 그 외 예시
# arr[:, 0:3]	#열 0, 1, 2 추출
# arr[:, ::2]	#짝수 열만 추출 (0, 2, 4)


# [참고]
# 넘파이 배열 전치(Transpose)를 이용한 방법 설명
# 전치 행렬을 구하고, 특정 열만 선택한 후
# 전치는 예전 행렬 수업 참고
# 행과 열을 바꿔주는 전치행렬로 바꾼 후 1행과 3행만 선택하고
# 다시 트랜스포즈(전치)해서 원래 모양으로 돌아온 것
transpose1 = arr.T[[1, 3]].T


print("\n.T (Transpose) 방식으로 열 1, 3 추출:")
print(transpose1)




NumPy 배열로 열 1, 3 추출:
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]
 [27 29]
 [32 34]
 [37 39]
 [42 44]
 [47 49]]

NumPy 배열로 열 1~3열 추출:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]
 [32 33 34]
 [37 38 39]
 [42 43 44]
 [47 48 49]]

NumPy 배열로 열 1~3열 추출:
[[12 13 14]
 [17 18 19]
 [22 23 24]]

.T (Transpose) 방식으로 열 1, 3 추출:
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]
 [27 29]
 [32 34]
 [37 39]
 [42 44]
 [47 49]]
