In [4]:
import numpy as np
a=[[10,20,30],[40,50,60],[70,80,90]]
an = np.array(a)
print(an)
print(a[0])
print(a[1])
print(a[2])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[10, 20, 30]
[40, 50, 60]
[70, 80, 90]
[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
